---
- hosts: 192.168.56.103
  become: true
  tasks:

    - name: start docker private registry
      command: docker run -d -p 5000:5000 --restart=always --name docker_registry registry:2

    - name: install epel release
      command: sudo yum install epel-release

    - name: install python -pip
      command: sudo yum install python-pip

    - name: install docker-py
      command: sudo pip install docker-py


    - name: pull an image
      docker_image:
        name: sonatype/nexus3

    - name: Tag and push to local registry
      docker_image:
     # Image will be centos:7
        name: sonatype/nexus3
     # Will be pushed to localhost:5000/centos:7
        repository: localhost:5000/nexus3
        push: yes
        source: local

    - name: start docker private registry
      command: docker run -d -p 8081:8081 --restart=always --name nexus sonatype/nexus3
