---
#- name: start docker private registry
#  command: docker run -d -p 5000:5000 --restart=always --name docker_registry registry:2
- name: install epel release
  command: yum install epel-release -y
- name: install python -pip
  command: yum install python-pip -y
- name: install docker-py
  command: pip install docker-py
- name: pull an image
  docker_image:
    name: sonatype/nexus3
- name: Tag and push to local registry
  docker_image:
    name: sonatype/nexus3
    repository: 'localhost:5000/nexus3'
    push: yes
    source: local
- name: start docker private registry
  command: docker run -d -p 8081:8081 --restart=always --name nexus sonatype/nexus3
