---
- name: le EPEL
  yum:
    name: epel-release
    state: present

- name: install python -pip
  command: yum install python-pip -y

- name: install docker-py
  command: pip install docker-py

- name: get container state
  docker_container_info:
    name: docker_registry
  register: result

- name: start docker private registry
  command: docker run -d -p 5000:5000 --restart=always --name docker_registry registry:2
  when: result.exists == False

- name: pull an image
  docker_image:
    name: sonatype/nexus3

- name: wait for docker_registry to come up
  uri:
    url: "http://localhost:5000"
    status_code: 200
  register: result
  until: result.status == 200
  retries: 60
  delay: 3

- name: Tag and push to local registry
  docker_image:
    name: sonatype/nexus3
    repository: 'localhost:5000/nexus3'
    push: yes
    source: local

- name: get container state
  docker_container_info:
    name: nexus
  register: resultn3

- name: start nexus3
  command: docker run -d -p 8081:8081 --restart=always --name nexus sonatype/nexus3
  when: resultn3.exists == False

- name: wait for nexus to come up
  uri:
    url: "http://localhost:8081"
    status_code: 200
  register: result
  until: result.status == 200
  retries: 60
  delay: 3
