---
<<<<<<< HEAD
# tasks file for groups_users
=======
- name: add docker group
  group:
    name: docker
    state: present

- name: add vagrant user to group
  user:
    name: vagrant
    group: docker
    append: yes
>>>>>>> 582df66cbcfe7024eba26af363b0269fee137984
