---
- hosts: 192.168.56.103
  tasks:
  - name: ensure everything is removed
    yum:
      name:
        - docker
        - docker-client
        - docker-client-latest
        - docker-common
        - docker-latest
        - docker-latest-logrotate
        - docker-logrotate
        - docker-engine
      state: absent
